### ISSUE TITLE
[bug] Missing `file://` protocol while running examples in Windows

### ISSUE THREAD

**Issue by hyf0** [dai-shi/wakuwork#28]
error output
```
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at new NodeError (node:internal/errors:399:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1059:11)
    at defaultResolve (node:internal/modules/esm/resolve:1135:3)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at u (file:///C:/Users/iheyu/Documents/GitHub/wakuwork/examples/01_counter.5.5/node_modules/@esbuild-kit/esm-loader/dist/index.js:1:2406)                   at nextResolve (node:internal/modules/esm/loader:163:28)
    at resolve (file:///C:/Users/iheyu/Documents/GitHub/wakuwork/dist/node-loader.js:1:238)                                                                     at async nextResolve (node:internal/modules/esm/loader:163:22)
    at async resolve (file:///C:/Users/iheyu/Documents/GitHub/wakuwork/examples/01_counter/node_modules/.pnpm/registry.npmmirror.com+react-server-dom-webpack@18.3.0-canary-aef7ce554-20230503_react-dom@18_4enxzw6ksfg63hwdnna6ipu25e/node_modules/react-server-dom-webpack/esm/react-server-dom-webpack-node-loader.production.min.js:34:10)                                            at async nextResolve (node:internal/modules/esm/loader:163:22)
    at async ESMLoader.resolve (node:internal/modules/esm/loader:838:24)      
    at async ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:7) {

  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
```

## Reproduce

1. clone https://github.com/dai-shi/wakuwork
2. in examples, run `pnpm dev`

@dai-shi I have found the cause and come out with a fix locally. But it's a Windows-specific problem, not sure if you would accept the fix.

**Comment by dai-shi** [comment]
Thanks for reporting. I don't have Windows, so can't confirm. If the fix is simple and doesn't break for others, please send a PR. Is it just for node-loader.ts?

**Comment by hyf0** [comment]
I think the problem is related to the loader.

A simple fix would be

Change code in
https://github.com/dai-shi/wakuwork/blob/69216678985ad371e998e4b17d90cb6a093ce2da/src/middleware/rscDev.ts#L19
 to
```js
  let entriesFile = path.join(dir, config.files?.entriesJs || "entries.js");
  if (process.platform === 'win32') {
    entriesFile = `file://${entriesFile}` 
  }
```

I think the fix is also applied for
 
https://github.com/dai-shi/wakuwork/blob/69216678985ad371e998e4b17d90cb6a093ce2da/src/middleware/rscPrd.ts#L22

when running `pnpm build`.

---

A general fix would be to use customize `import()`

```js
function xxxImport(path) {
  if (process.platform === 'win32' && isAbsolute(path)) {
    path = `file://${path}`
  }
  return import(path)
}
```

**Comment by dai-shi** [comment]
If that's the case,
```diff
-   const dir = path.resolve(config.devServer?.dir || ".");
+   const dir = (isWin32 ? "file://" : "") + path.resolve(config.devServer?.dir || ".");
```

would be what I think is good. We need to make `decodeId` workaround though.
